CLUSTAL multiple sequence alignment by MUSCLE (3.8)


6WX6_A           TGWSHPQFEKLKGGSSRGGGGGSGGSGGSGGS----------------------------
AKI70338.1       ------------------------------------------------------------
AAA35831.1       ------------------------------------------------------------
AKI70336.1       ------------------------------------------------------------
CAG32996.1       ------------------------------------------------------------
AIC54405.1       ------------------------------------------------------------
CAE11873.1       QFGGPAGLSLASTVFGRNRSGDSLPASDRPPISSPLATSGTIFSAISCFWDLPAPFLWLA
NP_000137.2      ------------------------------------------------------------
AAP36762.1       ------------------------------------------------------------
2FG4_A           ------------------------------------------------------------
                                                                             

6WX6_A           ------MSSQIRQNYSTDVEAAVNSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
AKI70338.1       ------MSSQIRQNYSTDVEAAVNSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
AAA35831.1       ------MSSQIRQNYSTDVEAAVNSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
AKI70336.1       ------MSSQIRQNYSTDVEAAVNSLVNLYLQASYIYLSLGFYFDRDDVALEGVSHFFRE
CAG32996.1       ------MSSQIRQNYSTDVEAAANSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
AIC54405.1       ------MSSQIRQNYSTDVEAAVNSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
CAE11873.1       PSCQPTMSSQIRQNYSTDVEAAVNSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
NP_000137.2      ------MSSQIRQNYSTDVEAAVNSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
AAP36762.1       ------MSSQIRQNYSTDVEAAVNSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
2FG4_A           -------SSQIRQNYSTDVEAAVNSLVNLYLQASYTYLSLGFYFDRDDVALEGVSHFFRE
                        ***************.************ ************************

6WX6_A           LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDAMKAAMALEKKLNQALLDL
AKI70338.1       LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDTMKAAMALEKKLNQALLDL
AAA35831.1       LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDAMKAAMTLEKKLNQALLDL
AKI70336.1       LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDAMKAAMALEKKLNQALLDL
CAG32996.1       LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDAMKAAMALEKKLNQALLDL
AIC54405.1       LAEEKREGYERLLKMQNQRGGRALFQDIKXPAEDEWGKTPDAMKAAMALEKKLNQALLDL
CAE11873.1       LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDAMKAAMALEKKLNQALLDL
NP_000137.2      LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDAMKAAMALEKKLNQALLDL
AAP36762.1       LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDAMKAAMALEKKLNQALLDL
2FG4_A           LAEEKREGYERLLKMQNQRGGRALFQDIKKPAEDEWGKTPDAMKAAMALEKKLNQALLDL
                 ***************************** ***********:*****:************

6WX6_A           HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLRH
AKI70338.1       HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
AAA35831.1       HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
AKI70336.1       HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
CAG32996.1       HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
AIC54405.1       HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
CAE11873.1       HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
NP_000137.2      HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
AAP36762.1       HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
2FG4_A           HALGSARTDPHLCDFLETHFLDEEVKLIKKMGDHLTNLHRLGGPEAGLGEYLFERLTLKH
                 **********************************************************.*

6WX6_A           DGGSGGSGGSGGSGGGASGGS
AKI70338.1       D--------------------
AAA35831.1       D--------------------
AKI70336.1       D--------------------
CAG32996.1       D--------------------
AIC54405.1       D--------------------
CAE11873.1       D--------------------
NP_000137.2      D--------------------
AAP36762.1       DL-------------------
2FG4_A           D--------------------
                 *                    
